package com.example.android.gridlayoutdemo;

import android.media.MediaPlayer;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;

public class MainActivity extends AppCompatActivity {

    public void buttonTapped(View view){


        int id = view.getId(); //Some raw id (very long number) generated by the system
        String ourId = view.getResources().getResourceEntryName(id); //Human readable id (previously customized by ourselves)

        int resourceId = getResources().getIdentifier(ourId, "raw", "com.example.android.gridlayoutdemo"); //Id passed as path

        MediaPlayer mediaPlayer = MediaPlayer.create(this, resourceId);
        mediaPlayer.start();

        Log.i("Raw id", Integer.toString(id));
        Log.i("Button tapped", ourId);
        Log.i("Path passed", Integer.toString(resourceId));
    }
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }
}
